version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: "comments-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Restapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abayomi
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  api:
    build: .
    container_name: "comments-rest-api"
    environment:
     DB_USERNAME : "postgres"
     DB_PASSWORD : "abayomi"
     DB_DB : "postgres"
     DB_TABLE : "Restapi"
     DB_PORT : "5432"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack


volumes:
   database_postgres:

networks:
   fullstack:
    driver: bridge




