---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-api
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: comments-api
  template:
    metadata:
      labels:
        name: comments-api
    spec:
      containers:
      - name: application
        image: "igwubor/comments-api:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        env:
          - name: DB_PORT
            value: ""
          - name: DB_HOST
            value: "newkinddatabase.cxlnxakyrpfx.us-east-1.rds.amazonaws.com"
          - name: DB_PASSWORD
            value: "1234567890"
          - name: DB_TABLE
            value: "defaultdb"
          - name: DB_USERNAME
            value: "5432"